# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
# deleteDatasources:
#   - name: Aerospike Prometheus
#     orgId: 1
#   - name: Aerospike Prometheus Alertmanager
#     orgId: 1

datasources:
  - name: "Aerospike Prometheus Alertmanager"
    type: camptocamp-prometheus-alertmanager-datasource
    access: proxy
    # orgId: 1
    url: http://alertmanager:9093
    editable: true
    isDefault: false

  - name: "Aerospike Prometheus"
    type: prometheus
    access: proxy
    # orgId: 1
    url: http://prometheus:9090
    editable: true
    isDefault: false
